server:
  runmode: debug                # 开发模式, debug, release, test
  port: 8080                    # HTTP绑定端口
  max_ping_count: 10            # pingServer函数尝试的次数
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: ginessential
  username: root
  password: root
  charset: utf8

